# -*- coding: utf-8 -*-
"""histogram-descriptors_demo_forGcolab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/ChemicalBatteryLab-Nitech/dxgem_day1day2/blob/main/histogram-descriptors_demo_forGcolab.ipynb

# ヒストグラム記述子の抽出

<br>
コードはこちらから：<BR>
https://github.com/ChemicalBatteryLab-NITech/composional-histogram-descriptor<BR>
https://github.com/ChemicalBatteryLab-Nitech/rdfadf<BR>

履歴<BR>
2022年5月6日　小山翼<BR>
2025年11月 中山（C言語→python化：RDF,ADF追加,  chemhistの改訂)<BR>
"""

!pip install chemhist
!pip install rdfadf

import numpy as np
import pandas as pd
import chemhist
from rdfadf.rdf import compute_general_rdf
from rdfadf.adf import compute_general_adf
from matplotlib import pyplot as plt

"""## Chemhist: ヒストグラム型組成記述子
【要ユーザー操作】　組成式を指定する
"""

# 実施例
chemvec, labels = chemhist.get_descriptor("LiCoO2")
print (labels)
print (chemvec)

plt.figure(figsize=(20,6))
plt.plot(chemvec)

"""## RDFADF: ヒストグラム型構造記述子

"""

# (1) URLからファイルをダウンロード（Google Colab環境の場合）
import urllib.request

url = "https://raw.githubusercontent.com/ChemicalBatteryLab-Nitech/dxgem_day1day2/main/data/LiCoO2.cif"
local_filename = "LiCoO2.cif"

urllib.request.urlretrieve(url, local_filename)
print("Downloaded:", local_filename)

# (2) ASEで読み込み
from ase.io import read
atoms = read(local_filename)
atoms

# RDFの計算例
r, gr,grs,gr2,gr2s,cr,crs = compute_general_rdf(atoms, "O", "O", rcut=10.0, bins=100, sigma=1)

plt.figure(figsize=(10,6))
plt.plot(r, gr2)
plt.plot(r, gr2s)

# ADFの計算例
r, adf,adfs = compute_general_adf(atoms, "s", "p", "p", rcut=2.8, bins=90, sigma=2)

plt.figure(figsize=(10,6))
plt.plot(r, adf)
plt.plot(r, adfs)