CONFIG = {
    "volcano": {
        "figsize": (10, 7),
        "scatter_alpha": 0.7,
        "scatter_color": "tab:blue",
        "scatter_marker": "o",
        "scatter_size": 30,
        "trend_line_style": "--",
        "trend_line_width": 1.3,
        "trend_left_color": "orange",
        "trend_right_color": "purple",
        "split_line_color": "gray",
        "split_line_style": ":",
        "split_line_width": 1,
        "split_marker_size": 12,
        "trend_samples": 50,
        "x_axis_limits": (0.0, 3.0),
        "grid": {"linestyle": "--", "linewidth": 0.5, "which": "both"},
        "xlim": (0, 3),
        "ylim": (-2, -0.5),
        "axes_label_fontsize": 11,
        "title_fontsize": 13,
        "legend_fontsize": 10,
        "annotation_fontsize": 8,
        "label_offsets": {
            "Ir": (10, 6),
            "Cr": (-10, 6),
            "Mn": (10, -6),
            "Pb": (-10, -6),
        },
        "title": "Volcano Plot",
        "xlabel_prefix": "Descriptor",
        "ylabel": "Activity (eV)",
    },
    "plot32": {
        "figsize": (10, 7),
        "scatter_alpha": 0.7,
        "colors": {
            "y1": "tab:orange",
            "y2": "tab:purple",
        },
        "markers": {
            "y1": "o",
            "y2": "^",
        },
        "scatter_size": 30,
        "line_style": "--",
        "line_width": 1.3,
        "grid": {"linestyle": "--", "linewidth": 0.5, "which": "both"},
        "title": "Scatter with Two Fitted Lines",
        "ylabel": "Energy (eV)",
        "axes_label_fontsize": 11,
        "title_fontsize": 13,
        "legend_fontsize": 10,
    },
}
