# -*- coding: utf-8 -*-
"""matminer_descriptors_distribute_forGcolab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/ChemicalBatteryLab-Nitech/dxgem_day1day2/blob/main/matminer_descriptors_distribute_forGcolab.ipynb

# Matminerによる組成記述子の抽出
Matminerは米国ローレンス・バークレー研究所で開発された記述子ツール。以下は組成記述子のいくつかを取得するためのスクリプト。詳細・引用先は　https://hackingmaterials.lbl.gov/matminer/
を参照のこと  

試作：中山研＠名工大
"""

# !pip install pymatgen==2023.12.18
# !pip install matminer==0.7.0
# !pip install numpy==1.26.0

##モジュールのインストール

# !pip install matminer

from matminer.featurizers.conversions import StrToComposition
from matminer.featurizers.composition import ElementProperty
from matminer.featurizers.conversions import CompositionToOxidComposition
from matminer.featurizers.composition import OxidationStates
from matminer.featurizers.composition import AtomicOrbitals
from matminer.featurizers.composition import Meredig, Stoichiometry, IonProperty, ValenceOrbital, AtomicPackingEfficiency

import pandas as pd
import os
import glob
import matplotlib.pyplot as plt

import time

"""【要ユーザー操作】　入力ファイル名の記述　　testdata.csv  を自身のファイル名に変更する"""

df = pd.read_csv('https://raw.githubusercontent.com/ChemicalBatteryLab-Nitech/dxgem_day1day2/main/data/testdata.csv')
print ("number of samples",len(df))
df.head()

"""【要ユーザー操作】　組成式が入っているラベルを指定する
（この例では： formula  大文字・小文字区別）
"""

formula="formula"
for i in range(len(df)):
    df[formula][i]

stc = StrToComposition()
ep_feat = ElementProperty.from_preset(preset_name="magpie")
ao_feat = AtomicOrbitals()
md_feat = Meredig()
st = Stoichiometry()
ip_feat = IonProperty()
vo_feat = ValenceOrbital()
ap_feat = AtomicPackingEfficiency()

n21 = stc.featurize_dataframe(df,formula)
n22 = ep_feat.featurize_dataframe(n21, col_id="composition")
n23=ao_feat.featurize_dataframe(n22, col_id="composition")
n24=md_feat.featurize_dataframe(n23, col_id="composition")
n25=st.featurize_dataframe(n24, col_id="composition")

n25.head()

"""【要ユーザー操作】　出力するファイル名入力のこと"""

n25.to_csv('testdata_matminer.csv', index=False)

# google colab ユーザー　（データのダウンロード）

from google.colab import files
files.download("testdata_matminer.csv")